In [ ]:
# Numpy Array 

#### Numerical Array

In [1]:
import numpy as np

In [3]:
np.array([5,9,13],ndmin = 3)

## ndmin = 3 /dimension = 3

array([[[ 5,  9, 13]]])

In [4]:
np.array([5,9,13],ndmin = 1)

## ndmin = 3 / dimension = 1

array([ 5,  9, 13])

In [5]:
np.array([5,9,13])

## you can leave to specify if it one dimension 

array([ 5,  9, 13])

In [43]:
data = np.array([ [1,2,3],[4,5,6],[42,33,55]])

In [45]:
data


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [42, 33, 55]])

### change the dtypes

In [8]:
data = np.array([ [1,2,3],[4,5,6],[42,33,55]], dtype = float)

In [9]:
data

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [42., 33., 55.]])

### How use __mat()__ and create a matrix

In [47]:
# create a matrix array using .mat (matrix)

a = np.array(np.mat('1,2,3;3,4,5;0,1,2;33,22,44'))

In [51]:
a

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [ 0,  1,  2],
       [33, 22, 44]])

### convert a list into an array

In [56]:
# 1)

b =[1,2]

np.array(a)

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [ 0,  1,  2],
       [33, 22, 44]])

## Using __asanyarray()__ method

In [57]:
# 2)
c = np.asanyarray(b)

In [58]:
c, c.ndim

(array([1, 2]), 1)

In [52]:
xx = np.array([5,9,13],ndmin = 3)


In [53]:

## How to see the dimension ?

xx.ndim

3

In [17]:
xx.shape

## here 3 in the answer refer to the dimension

(1, 1, 3)

In [18]:
data.shape

(3, 3)

# __Arange__ in numpy

### Because __range()__ use only integer numbers but __arange()__ of numpy can use __float__ numbers

In [19]:
z = np.arange(2,10.5,.4)

In [20]:
print(z)

[ 2.   2.4  2.8  3.2  3.6  4.   4.4  4.8  5.2  5.6  6.   6.4  6.8  7.2
  7.6  8.   8.4  8.8  9.2  9.6 10.  10.4]


In [21]:
## Reverse
z[:: -1]

array([10.4, 10. ,  9.6,  9.2,  8.8,  8.4,  8. ,  7.6,  7.2,  6.8,  6.4,
        6. ,  5.6,  5.2,  4.8,  4.4,  4. ,  3.6,  3.2,  2.8,  2.4,  2. ])

In [22]:
##  using for loop in arange
for x1 in np.arange(2,10.5,.4):
    if x1 == 7.2 :
        print(x1)
    else:
        continue

In [23]:
print('Every 5th number from 50 in reverse order is\n',np.arange(50,-1,-5))

Every 5th number from 50 in reverse order is
 [50 45 40 35 30 25 20 15 10  5  0]


## Linear __space__ number

In [60]:
## from 1 to 100 , I need 6 news and space interval between  is same them.

print(np.linspace(1,100,6))

[  1.   20.8  40.6  60.4  80.2 100. ]


# How to create a matrix ?

In [25]:
print(" Vector of zeros\n --------------")
print(np.zeros(5))

 Vector of zeros
 --------------
[0. 0. 0. 0. 0.]


In [62]:
print(" Vector of zeros\n --------------")

print(np.zeros((3,3)))
print('-'*16)

 Vector of zeros
 --------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
----------------


In [63]:
print(np.ones((4,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [64]:
print(5*np.ones((5,2)))

[[5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]]


In [67]:
xyz = np.ones((3,2))*3
xyz

array([[3., 3.],
       [3., 3.],
       [3., 3.]])

### How to use  __eye()__ method

In [29]:
## help you find the unit matrix

mat = np.eye(3,3)
print('Identity matrix of dimension',mat.shape)
print(mat)

Identity matrix of dimension (3, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [70]:
## you can add end point to linspace() method


np.linspace(2.0,3.0,num=8, endpoint= False)

array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875])

## retstep() give the difference number of interval

In [71]:

np.linspace(2.0,3.0,num= 10, retstep= True ,endpoint = False)



(array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9]), 0.1)

In [32]:
## how to use logspance()

np.logspace(2.0,3.0,num= 4, endpoint= False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

# constract Diagonal matrix


In [33]:
y = np.arange(20)
y
              

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [72]:
x = np.arange(30).reshape(6,5)

In [73]:
x 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [74]:
# get diag() of x

np.diag(x)

array([ 0,  6, 12, 18, 24])

# How to generate Random numbers

#### andom.rand() / for positive numbers

In [77]:
print('Random number generation (from Uniform distribution)\n','-'*56)
print(np.random.rand(5,5))

Random number generation (from Uniform distribution)
 --------------------------------------------------------
[[0.28994693 0.54616047 0.52135182 0.74364793 0.10222946]
 [0.14639178 0.39782547 0.18933967 0.5551343  0.56678794]
 [0.59476236 0.02640641 0.54150911 0.08689164 0.29942403]
 [0.93527395 0.5693244  0.75730355 0.28365026 0.29173127]
 [0.21904976 0.76519046 0.6255401  0.03669386 0.10694388]]


#### andom.randn()  / for negative numbers
 

In [80]:
print('Number from Normal distribution with zero mean and standard deviation 1.\n','-'*66)
print(np.random.randn(5,3))

Number from Normal distribution with zero mean and standard deviation 1.
 ------------------------------------------------------------------
[[-0.09337321 -0.18116373  1.23990751]
 [-1.01521705  0.98345455  0.65253643]
 [-1.88671364 -0.30297664 -1.56109944]
 [-0.26268406  1.09961137  0.88242411]
 [-0.22343909  0.79698133  1.68332871]]


#### random.randint()  / for only integer numbers


In [81]:
## first two are start and endpoint and the last  arg is number of numbers
# you need 
print(np.random.randint(0,100,20))

[67 33 58 17 91 42 73 40 70 60 22 96 61 29 47  1 48 27 97 42]


## Random integer matrix

In [83]:
print("\n Randoom integer matrix\n",'-'*18)
print(np.random.randint(1,8,(3,3)))


 Randoom integer matrix
 ------------------
[[5 7 7]
 [3 2 5]
 [3 1 5]]


In [86]:
z = np.random.randint(1,3,(3,3))

In [87]:
z

array([[1, 1, 2],
       [1, 2, 2],
       [1, 1, 2]])

# __Reshaping()__ method

In [108]:
import numpy as np

from numpy.random import randint as ri


In [89]:
xx = ri(1,100,18)

In [90]:
print(xx)

[13 88 44 81 11 84 25  2 28 41 65 79 40 34 30 27 75 99]


In [92]:
## reshape(3,4) = create  matrix with (3 = rows) and (4 columns)
xx.reshape(6,3)

    

array([[13, 88, 44],
       [81, 11, 84],
       [25,  2, 28],
       [41, 65, 79],
       [40, 34, 30],
       [27, 75, 99]])

In [93]:
m = np.sort(xx)

In [94]:
m

array([ 2, 11, 13, 25, 27, 28, 30, 34, 40, 41, 44, 65, 75, 79, 81, 84, 88,
       99])

In [95]:
xx.max()

99

In [97]:
yy = xx.reshape(6,3)

In [8]:
print(yy)

[[77 94 93 73 20]
 [50 22 58 62 25]
 [45 24 96 96  3]
 [31 14 37 40 57]
 [51 23 81 68 48]]


# __sort()__ in matrix with argument __axis__ 0 or 1

In [102]:
# How to sort columns  wise

dd = np.sort(yy, axis = 0)

In [103]:
dd

array([[13,  2, 28],
       [25, 11, 30],
       [27, 34, 44],
       [40, 65, 79],
       [41, 75, 84],
       [81, 88, 99]])

## Indexing and slicing

In [104]:
arr = np.arange(0,11)

In [105]:
print('Array:', arr)

Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [56]:
print('Element at 7th index is :',arr[7])

Element at 7th index is : 7


In [57]:
#Slicing

print('Elements for 3rd to 5th index are:',arr[3:6])

Elements for 3rd to 5th index are: [3 4 5]


In [106]:
print('Element up to 4th index :',arr[4:8])

Element up to 4th index : [4 5 6 7]


In [107]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## print one and __scape__ after 

In [60]:

## print one and scape after 

print('Element  index :',arr[1::2])


Element up to 4th index : [1 3 5 7 9]


In [61]:
arr1 = np.arange(0,21,2)

In [62]:
arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [63]:
## without semi-column

v = arr1[[2,3,4]]

In [64]:
v

array([4, 6, 8])

In [65]:
print(type(arr1))

<class 'numpy.ndarray'>


In [66]:
dd

array([[21, 48, 24,  3,  2],
       [25, 52, 35, 31, 30],
       [49, 57, 74, 33, 34],
       [60, 66, 79, 56, 38],
       [61, 80, 88, 58, 58]])

In [67]:
## Slicing data from a matrix [rows][columns]

dd[2][0]

49

## [start-row:end-row, cols_start:cols_end ]

In [76]:
# [start-row:end-row, cols_start:cols_end ]

dd[1:3, 0:2]


array([[25, 52],
       [49, 57]])

In [93]:
#### 
dd[3:5,3:5]

array([[56, 38],
       [58, 58]])

## Condition base on the dataset

In [10]:
yy

array([[77, 94, 93, 73, 20],
       [50, 22, 58, 62, 25],
       [45, 24, 96, 96,  3],
       [31, 14, 37, 40, 57],
       [51, 23, 81, 68, 48]])

In [11]:
print( yy > 50 )

[[ True  True  True  True False]
 [False False  True  True False]
 [False False  True  True False]
 [False False False False  True]
 [ True False  True  True False]]


## Using __matrix[matrix > 45]__

In [39]:
print('\nNumber great than 50 are:\n','-'*36)

print(yy[yy > 50])



Number great than 50 are:
 ------------------------------------
[77 94 93 73 58 62 96 96 57 51 81 68]


# how to make transpot matrix __T__

In [31]:
add_max = np.array([[0,1,2,3,4],[0,11,22,33,44]])
add_max

array([[ 0,  1,  2,  3,  4],
       [ 0, 11, 22, 33, 44]])

In [30]:
print(add_max.T)

[[ 0  0]
 [ 1 11]
 [ 2 22]
 [ 3 33]
 [ 4 44]]


In [42]:
add_max[:,1:4]

array([[ 1,  2,  3],
       [11, 22, 33]])

In [109]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)

In [110]:
mat2 = np.array(ri(1,7,9)).reshape(3,3)

In [115]:

print('\n',mat1,'\n','-'*8,'\n',mat2)



 [[8 9 7]
 [9 4 5]
 [5 4 8]] 
 -------- 
 [[4 5 2]
 [1 4 6]
 [2 5 6]]


## array vectorization 

In [116]:
 xyz = mat1 + mat2

In [117]:
xyz

array([[12, 14,  9],
       [10,  8, 11],
       [ 7,  9, 14]])

In [120]:
xyz1 = mat1 * mat2

In [121]:
xyz1

array([[32, 45, 14],
       [ 9, 16, 30],
       [10, 20, 48]])